bookingsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login/', LoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users', include('users.urls', namespace='users')),
    path('serviceprovider/', include('serviceprovider.urls', namespace='serviceprovider')),
    path('', include('home.urls', namespace='home')),
]

home/urls.py
from django.urls import path
from .views import *

app_name='home'

urlpatterns = [
    path('', index, name='index'),
    path('home', after_login, name='home'),
    path('auditorium-info', auditorium_info, name='auditorium-info'),
    path('auditoriums', auditoriums, name='auditoriums'),
    path('auditorium-book', auditorium_book, name='auditorium-book'),
    path('auditorium-cancel/<int:id>', auditorium_cancel, name='auditorium-cancel'),
    path('connected/<int:id>', connected, name='connected'),
    path('remove/<int:id>', remove, name='remove'),
    path('contact', contact, name='contact'),
]

serviceprovider/urls.py
from unicodedata import name
from django.urls import path
from .views import *

app_name='serviceprovider'
urlpatterns = [
    path('add-auditorium', add_auditorium, name='add-auditorium'),
    path('update-auditorium/<int:id>', update_auditorium, name='update-auditorium'),
    path('auditorium-dashboard/<str:user>/<int:id>', auditorium_dashboard, name='auditorium-dashboard'),
]

users/urls.py
from django.urls import path
from .views import *

app_name='users'
urlpatterns = [
    path('signup-client', signup_client, name='signup-client'),
    path('signup-serviceprovider', signup_serviceprovider, name='signup-serviceprovider'),
    path('profile', profile, name='profile'),
    path('dashboard', dashboard, name='dashboard'),
    path('dashboard-client', dashboard_client, name='dashboard-client'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from .utils import *


class User(AbstractUser):
    username = models.CharField(
        max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f'{self.email}'

class AccType(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.user}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    adhar = models.CharField(max_length=12)
    pdf_adhar = models.FileField(upload_to=get_aadhar_upload_to, null= False,)
    pic = models.ImageField(upload_to=get_pic_upload_to, null=False)
    passbook = models.ImageField(upload_to=get_passbook_upload_to, null=False)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pin = models.CharField(max_length=10)
    
    def __str__(self):
        return f'{self.user}'

class ProfileStatus(models.Model):
    choices = (
        ('Accepted', 'Accepted'),
        ('Deline', 'Deline')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=9, choices=choices)

    def __str__(self):
        return f'{self.user}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *



class SignupForm(UserCreationForm):
    class Meta:
       model = User
       fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2') 
    def __init__(self, *args, **kargs):
        super(SignupForm, self).__init__(*args, **kargs)
        self.fields['username'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Username'
        })

        self.fields['first_name'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'First Name',
            'name' : 'first_name',
            'id' : 'first_name'
        })

        self.fields['last_name'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Last Name',
            'name' : 'last_name',
            'id' : 'last_name',
        })
        self.fields['email'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Email',
            'name' : 'email',
            'id' : 'email',
        })

        self.fields['password1'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Password',
            'name' : 'password1',
            'id' : 'password1',
        })

        self.fields['password2'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Confirm Password',
            'name' : 'password2',
            'id' : 'password2',
        })
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'name', 'phone', 'email', 'adhar', 'pdf_adhar', 'pic', 'passbook',
            'address1', 'address2', 'district', 'state', 'pin'
        ) 
    def __init__(self, *args, **kargs):
        super(ProfileForm, self).__init__(*args, **kargs)
        self.fields['name'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Name',
            'name' : 'name',
            'id' : 'name'
        })
        self.fields['phone'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Phone Number',
            'name' : 'phone',
            'id' : 'phone'
        })
        self.fields['email'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Email',
            'name' : 'email',
            'id' : 'email'
        })
        self.fields['adhar'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Aadhar',
            'name' : 'adhar',
            'id' : 'adhar'
        })
        self.fields['pdf_adhar'].widget.attrs.update({
            'class' : 'form-control',
            'name' : 'pdf_adhar',
            'id' : 'pdf_adhar'
        })
        self.fields['pic'].widget.attrs.update({
            'class' : 'form-control',
            'name' : 'pic',
            'id' : 'pic'
        })
        self.fields['passbook'].widget.attrs.update({
            'class' : 'form-control',
            'name' : 'passbook',
            'id' : 'passbook'
        })
        self.fields['address1'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Address1',
            'name' : 'address1',
            'id' : 'address1'
        })
        self.fields['address2'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Address2',
            'name' : 'address2',
            'id' : 'address2'
        })
        self.fields['district'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'District',
            'name' : 'district',
            'id' : 'district'
        })
        self.fields['state'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'State',
            'name' : 'state',
            'id' : 'state'
        })
        self.fields['pin'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'PIN code',
            'name' : 'pin',
            'id' : 'pin'
        })
        

users/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import date, datetime

from .forms import *
from .models import *
from serviceprovider.models import Auditorium, Book

# Create your views here.

#client
def signup_client(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            print("Success")
            email = form.cleaned_data['email']
            form.save()
            user = User.objects.get(email=email)
            acc = AccType.objects.create(user=user, type='client')
            acc.save()
            return redirect('accounts/login')
    return render(request, 'signup_client.html', {'form': form})

#service provider
def signup_serviceprovider(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            print("Success")
            email = form.cleaned_data['email']
            form.save()
            user = User.objects.get(email=email)
            acc = AccType.objects.create(user=user, type='serviceprovider')
            acc.save()
            return redirect('accounts/login')
    return render(request, 'signup_service.html', {'form': form})

@login_required(login_url='users:signup-serviceprovider')
def dashboard(request):
    user = User.objects.get(email=request.user)
    join_date = user.date_joined.date()
    if abs((date.today() - join_date).days) <= 365:
        pay = 'true'
    else:
        pay = 'false'
    auditoriums = Auditorium.objects.filter(user=user)
    try:
        profile_status = ProfileStatus.objects.get(user=user)
        if profile_status.status == "Accepted":
            status = 'accepted'
        else:
            status = 'deline'
    except:
        status = 'pending'

    context = {
        'profile' : Profile.objects.get(user=user).pic,
        'first_name' : user.first_name,
        'last_name' : user.last_name,
        'username' : user.username,
        'email' : user.email,
        'status' : status,
        'pay' : pay,
        'auditoriums': auditoriums,
        'date' : date.today()
    }
    
    return render(request, 'dashboard_service.html', context=context)

@login_required(login_url='users:signup-serviceprovider')
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        name = request.POST['name']
        phone = request.POST['phone']
        email = request.POST['email']
        adhar = request.POST['adhar']
        pdf_adhar = request.FILES['pdf_adhar']
        pic = request.FILES['pic']
        passbook = request.FILES['passbook']
        address1 = request.POST['address1']
        address2 = request.POST['address2']
        district = request.POST['district']
        state = request.POST['state']
        pin = request.POST['pin']
        user = request.user
        profile = Profile.objects.create(
            user=user,
            name=name,
            phone=phone,
            email=email,
            adhar=adhar,
            pdf_adhar=pdf_adhar,
            pic=pic,
            passbook=passbook,
            address1=address1,
            address2=address2,
            district=district,
            state=state,
            pin=pin
        )
        profile.save()
        return redirect('users:dashboard')
    return render(request, 'profile.html', {'form': ProfileForm()})

@login_required(login_url='users:signup-client')
def dashboard_client(request):
    user = request.user
    books = Book.objects.filter(user=user)
    user = User.objects.get(email=user)
    context = {
        'books':books, 
        'user':user,
        'date' : date.today()
        }
    return render(request, 'dashboard_client.html', context=context)

users/templates/dashboard_client.html
<html>
    <head>
       <!-- CSS only -->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <style>
           .inf-content{
            border:1px solid #DDDDDD;
            -webkit-border-radius:10px;
            -moz-border-radius:10px;
            border-radius:10px;
            box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
                        }			                                                      
      </style>
    </head>
    <body>
        <div class="container bootstrap snippets bootdey">
            <div class="panel-body inf-content">
                <div class="row">
                    {% comment %} 
                    <div class="col-md-4">
                        <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="{{profile}}" data-original-title="Usuario"> 
                    </div>
                    <div class="col-md-6"> 
                    {% endcomment %}
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Information                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                                <a class="btn btn-primary" href="accounts/logout" role="button">Logout</a>                           
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Username                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{user.username}}
                                        </td>
                                    </tr>
                                    <tr>    
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-user  text-primary"></span>    
                                                First Name                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{ user.first_name }}     
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                                Last Name                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{user.last_name}}
                                        </td>
                                    </tr>

                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                                Email                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{user.email}} 
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>      
        </div>

        <br>
        {% comment %}==================== booking section ======================={% endcomment %}

        <div class="container bootstrap snippets bootdey">
            <div class="panel-body inf-content">
                <div class="row">
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <thead>
                                    <h5>
                                        Booking History
                                    </h5> 
                                </thead>
                                <tbody>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Auditorium</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Date</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Time Slot</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Contact</span>                                                  
                                            </strong>
                                        </td>
                                    </tr>
                                    {% for book in books %}
                                    <tr>        
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.auditorium.name}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.date}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.from_time}} - {{book.to_time}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.auditorium.number}}</span>                                                    
                                        </td>
                                        <td>
                                            {% if date >= book.date %}
                                            <p> You Can't Cancel This Slot </p>
                                            {% else %}
                                            <a class="btn btn-danger" href="{% url 'home:auditorium-cancel' book.id %}">Cancel</a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>      
        </div>                                    

    </body>
</html>

users/templates/dashboard_service.html
<html>
    <head>
       <!-- CSS only -->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <style>
           .inf-content{
            border:1px solid #DDDDDD;
            -webkit-border-radius:10px;
            -moz-border-radius:10px;
            border-radius:10px;
            box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
                        }			                                                      
      </style>
    </head>
    <body>
        <div class="container bootstrap snippets bootdey">
            <div class="panel-body inf-content">
                <div class="row">
                    <div class="col-md-4">
                        <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="{{profile}}" data-original-title="Usuario"> 
                    </div>
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Information                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                                <a class="btn btn-primary" href='accounts/logout' role="button">Logout</a>                           
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Status                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {% if 'accepted' in status %}  
                                            *You are now a service Provider
                                            {% elif 'pending' in status %}  
                                            *Account verification is pending
                                            {% else %}  
                                            *Account Blocked 
                                            {% endif %}
                                            
                                        </td>
                                    </tr>
                                    <tr>    
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-user  text-primary"></span>    
                                                Name                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{ first_name }}     
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                                Lastname                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{last_name}}  
                                        </td>
                                    </tr>

                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                                Username                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{username}} 
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                                Email                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                        {{email}} 
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                                For Support                                              
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                        admin@admin.com 
                                        </td>
                                    </tr>
                                    {% if 'accepted' in status and 'true' in pay%}  
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                                Add Your Auditorium                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                        <a class="btn btn-primary" href="{% url 'serviceprovider:add-auditorium' %}" role="button">ADD</a> 
                                        </td>
                                    </tr>
                                    {% endif %}
                                    {% if 'false' in pay %}
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                                Pay Now                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            <form><script src="https://checkout.razorpay.com/v1/payment-button.js" data-payment_button_id="pl_ICg7J2k13T7BfD" async> </script> </form>
                                        </td>
                                    </tr>
                                    {%endif%}
                                </tbody>
                            </table>
                        </div>
                        {% if 'accepted' in status and 'true' in pay %}
                        <div class="row">
                            {% for auditorium in auditoriums %}
                            <div class="card" style="width: 18rem;">
                                {% comment %} <img class="card-img-top" src="{{auditorium.catelog}}" alt="Card image cap"> {% endcomment %}
                                <div class="card-body">
                                    <h5 class="card-title">{{auditorium.name}}</h5>
                                    {% comment %} <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> {% endcomment %}
                                    <a href="serviceprovider/auditorium-dashboard/{{auditorium.user}}/{{auditorium.id}}" class="btn btn-primary">Dashboard</a>
                                </div>
                            </div>
                            {%endfor%}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>      
        </div>                                        
    </body>
</html>