bookingsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login/', LoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users', include('users.urls', namespace='users')),
    path('serviceprovider/', include('serviceprovider.urls', namespace='serviceprovider')),
    path('', include('home.urls', namespace='home')),
]

home/urls.py
from django.urls import path
from .views import *

app_name='home'

urlpatterns = [
    path('', index, name='index'),
    path('home', after_login, name='home'),
    path('auditorium-info', auditorium_info, name='auditorium-info'),
    path('auditoriums', auditoriums, name='auditoriums'),
    path('auditorium-book', auditorium_book, name='auditorium-book'),
    path('auditorium-cancel/<int:id>', auditorium_cancel, name='auditorium-cancel'),
    path('connected/<int:id>', connected, name='connected'),
    path('remove/<int:id>', remove, name='remove'),
    path('contact', contact, name='contact'),
]

serviceprovider/urls.py
from unicodedata import name
from django.urls import path
from .views import *

app_name='serviceprovider'
urlpatterns = [
    path('add-auditorium', add_auditorium, name='add-auditorium'),
    path('update-auditorium/<int:id>', update_auditorium, name='update-auditorium'),
    path('auditorium-dashboard/<str:user>/<int:id>', auditorium_dashboard, name='auditorium-dashboard'),
]

users/urls.py
from django.urls import path
from .views import *

app_name='users'
urlpatterns = [
    path('signup-client', signup_client, name='signup-client'),
    path('signup-serviceprovider', signup_serviceprovider, name='signup-serviceprovider'),
    path('profile', profile, name='profile'),
    path('dashboard', dashboard, name='dashboard'),
    path('dashboard-client', dashboard_client, name='dashboard-client'),
]

serviceprovider/models.py
import re
from django.db import models
from users.models import *
from .utils import *
# Create your models here.

class Auditorium(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    catelog = models.ImageField(upload_to=get_catelog_upload_to)
    about = models.TextField(max_length=300)
    number = models.CharField(max_length=15)
    email = models.EmailField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    street = models.CharField(max_length=20)
    district = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pin = models.CharField(max_length=10)
    post = models.CharField(max_length=20)

    def __str__(self) -> str:
        return f'{self.name}-{self.user}'


class Preview(models.Model):
    auditorium = models.ForeignKey(Auditorium, on_delete=models.CASCADE)
    images = models.ImageField(upload_to=get_preview_upload_to)

    def __str__(self) -> str:
        return f'{self.auditorium}'

class Book(models.Model):
    auditorium = models.ForeignKey(Auditorium, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=30)
    book_number = models.CharField(max_length=15)
    book_email = models.EmailField()
    date = models.DateField()
    from_time = models.TimeField()
    to_time = models.TimeField()
    message = models.TextField(max_length=200)
    connected = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.auditorium}'

serviceprovider/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import *
class DateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'book_name',
            'book_number',
            'book_email',
            'date', 
            'from_time', 
            'to_time'
            )

    def __init__(self, *args, **kargs):
        super(DateForm, self).__init__(*args, **kargs)
        self.fields['book_name'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Your Name'
        })
        self.fields['book_number'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Your Phone Number'
        })
        self.fields['book_email'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Your Email'
        })
        self.fields['date'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'Date (YYYY-MM-DD)'
        })
        self.fields['from_time'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'From Time (HH:MM:SS)'
        })
        self.fields['to_time'].widget.attrs.update({
            'class' : 'form-control',
            'placeholder' : 'To Time (HH:MM:SS)'
        })
        

serviceprovider/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import *

# Create your views here.

@login_required
def add_auditorium(request):
    if request.method == 'POST':
        user = request.user
        email = ''
        name = request.POST['name']
        catelog = request.FILES.get('catelog')
        about = request.POST['about']
        number = request.POST['number']
        email = request.POST['email']
        price = request.POST['price']
        street = request.POST['street']
        district = request.POST['district']
        state = request.POST['state']
        pin = request.POST['pin']
        post = request.POST['post']
        images = request.FILES.getlist('images')

        Auditorium.objects.create(
            user = user,
            name = name,
            catelog = catelog,
            about = about,
            number = number,
            email = email,
            price = price,
            street = street,
            district = district,
            state = state,
            pin = pin,
            post = post
        )

        auditoriums = Auditorium.objects.filter(user=user)
        for auditorium in auditoriums:
            if auditorium.name == name:
                for image in images:
                    Preview.objects.create(
                        auditorium = auditorium,
                        images = image
                    )        
        return redirect('users:dashboard')

    return render(request, 'auditorium.html')

@login_required
def auditorium_dashboard(request, user, id):
    auditorium = Auditorium.objects.get(id=id)
    books = Book.objects.filter(auditorium=auditorium)
    context = {'auditorium':auditorium, 'books':books}
    return render(request, 'auditorium_dashboard.html', context=context)

@login_required
def update_auditorium(request,id):
    if request.method == 'POST':
        auditorium = Auditorium.objects.get(id=id)
        user = request.user
        auditorium.name = request.POST['name']
        catelog = request.FILES.get('catelog')
        if catelog != None:
            auditorium.catelog = catelog
        auditorium.about = request.POST['about']
        auditorium.number = request.POST['number']
        auditorium.email = request.POST['email']
        auditorium.price = request.POST['price']
        auditorium.street = request.POST['street']
        auditorium.district = request.POST['district']
        auditorium.state = request.POST['state']
        auditorium.pin = request.POST['pin']
        auditorium.post = request.POST['post']
        auditorium.save()
        images = request.FILES.getlist('images')

        if images != []:
            previews = Preview.objects.filter(auditorium=auditorium) 
            for preview in previews:
                preview.delete()

            for image in images:
                Preview.objects.create(
                    auditorium = auditorium,
                    images = image
                )  
        return redirect(f'../auditorium-dashboard/{request.user}/{id}')

        
    data = Auditorium.objects.get(id=id)
    return render(request, 'update_auditorium.html', {'data' : data})

serviceprovider/templates/auditorium.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link href="{% static 'assets/css/signup.css' %}" rel="stylesheet">
</head>
<body>
<div class="signup-form">
    <form enctype="multipart/form-data" method="post">
    
    {% csrf_token %}

        <h2> Upload Auditorium Data </h2>
		<p>Please fill in this form to add your auditorum in this platform!</p>

		<hr>

        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-user"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="name" placeholder="Name of Auditorium" required="required">
			</div>
        </div>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
                <textarea name="about" id="" cols="30" rows="10" class="form-control" placeholder="About your Auditorium"></textarea>
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="number" placeholder="Contact Number" required="required">
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="email" class="form-control" name="email" placeholder="Contact Email">
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="street" placeholder="Streeet Name">
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="district" placeholder="District">
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="state" placeholder="State">
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="pin" placeholder="Pin Code">
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="post" placeholder="Post Office">
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
                <div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
            	<input type="text" class="form-control" name="price" placeholder="Price/hour" required="required">
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
                <label class="form-label" for="customFile">Upload photo for catelog</label>
				<input type="file" name="catelog">
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<label class="form-label" for="customFile">Upload Some Previews</label> <br>
				<input type="file" name="images" multiple>
			</div>
        </div> 
        
        
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg">Upload</button>
        </div>

    </form>
</div>
</body>
</html>

serviceprovider/templates/auditorium_dashboard.html
<html>
    <head>
       <!-- CSS only -->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <style>
           .inf-content{
            border:1px solid #DDDDDD;
            -webkit-border-radius:10px;
            -moz-border-radius:10px;
            border-radius:10px;
            box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
                        }			                                                      
      </style>
    </head>
    <body>
        <div class="container bootstrap snippets bootdey">
            <div class="panel-body inf-content">
                <div class="row">
                    {% comment %} 
                    <div class="col-md-4">
                        <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="{{profile}}" data-original-title="Usuario"> 
                    </div>
                    <div class="col-md-6"> 
                    {% endcomment %}
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Information                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            <a class="btn btn-primary" href="{% url 'users:dashboard' %}" role="button">Back</a>
                                            &nbsp; &nbsp; 
                                            <a class="btn btn-danger" href="{% url 'serviceprovider:update-auditorium' auditorium.id %}">Update Data</a> 
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                                Name                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{auditorium.name}}
                                        </td>
                                    </tr>
                                    <tr>    
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-user  text-primary"></span>    
                                                Price/hour                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{ auditorium.price }}     
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                                Address                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{auditorium.district}}, {{auditorium.state}}, {{auditorium.post}}, {{auditorium.pin}}  
                                        </td>
                                    </tr>

                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                                Contact Number                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{auditorium.number}} 
                                        </td>
                                    </tr>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                                Contact Email                                                
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            {{auditorium.email}} 
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>      
        </div>

        <br>
        {% comment %}==================== booking section ======================={% endcomment %}

        <div class="container bootstrap snippets bootdey">
            <div class="panel-body inf-content">
                <div class="row">
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <thead>
                                    <h5>
                                        Booking Table
                                    </h5> 
                                </thead>
                                <tbody>
                                    <tr>        
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Date</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Time Slote</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Name</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Number</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Email</span>                                                  
                                            </strong>
                                        </td>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-asterisk">Massage</span>                                                  
                                            </strong>
                                        </td>
                                    </tr>
                                    {% for book in books %}
                                    <tr>        
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.date}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.from_time}} - {{book.to_time}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.book_name}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.book_number}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.book_email}}</span>                                                    
                                        </td>
                                        <td>
                                            <span class="glyphicon glyphicon-asterisk text-primary">{{book.message}}</span>                                                    
                                        </td>
                                        <td>
                                            {% if book.connected == False %}
                                            <a class="btn btn-primary" href="{% url 'home:connected' book.id %}">Connected</a> 
                                            {% elif book.connected == True %}
                                            <a class="btn btn-danger" href="{% url 'home:remove' book.id %}">Spam</a> 
                                            {% elif date >= book.date%}
                                            <a class="btn btn-primary" href="{% url 'home:remove' book.id %}">Clear</a> 
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>      
        </div>                                    

    </body>
</html>

serviceprovider/templates/update_auditorium.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link href="{% static 'assets/css/signup.css' %}" rel="stylesheet">
</head>
<body>
<div class="signup-form">
    <form enctype="multipart/form-data" method="post">
    
    {% csrf_token %}

        <h2> Update Auditorium Data </h2>

		<hr>

        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-user"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="name" placeholder="Name of Auditorium" required="required" value={{data.name}}>
			</div>
        </div>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
                <textarea name="about" id="" cols="30" rows="10" class="form-control" placeholder="About your Auditorium">{{data.about}}</textarea>
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="number" placeholder="Contact Number" required="required" value={{data.number}}>
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="email" class="form-control" name="email" placeholder="Contact Email" value={{data.email}}>
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="street" placeholder="Streeet Name" value={{data.street}}>
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="district" placeholder="District" value={{data.district}}>
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="state" placeholder="State" value={{data.state}}>
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="pin" placeholder="Pin Code" value={{data.pin}}>
			</div>
        </div> 
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
				<input type="text" class="form-control" name="post" placeholder="Post Office" value={{data.post}}>
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
                <div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-chevron-circle-right"></span>
					</span>                    
				</div>
            	<input type="text" class="form-control" name="price" placeholder="Price/hour" required="required" value={{data.price}}>
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
                <label class="form-label" for="customFile">Upload photo for catelog</label>
				<input type="file" name="catelog">
			</div>
        </div> 
        <div class="form-group">
			<div class="input-group">
				<label class="form-label" for="customFile">Upload Some Previews</label> <br>
				<input type="file" name="images" multiple>
			</div>
        </div> 
        
        
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg">Update</button>
        </div>

    </form>
</div>
</body>
</html>